### PR TITLE
Add accessible_output for speaking to screen readers.

### LINKED ISSUE #5: output backend for Linux
there currently is no speech available under Linux. An output backend should be provided to work under Linux to support screen reader like speech feedback. I know that there was speech dispatcher available under Linux some years ago, but I don't know what the current options would be. Maybe embedding eSpeak directly would be an option.

### PR DESCRIPTION
**Pull request by trypsynth**
Closes #5 and #6

Note that I wasn't exactly sure how to initialize the backend, so there might be some unnecessary code in app.py for loading it. If this is the case, let me know and I can remove it.

### CODE REVIEW

**Comment by trypsynth** [comment]
@Timtam, the AppVeyor check seems to have failed, because I'm pulling the latest AO2 code from GitHub, that haven't been published to PyPi yet. I'm doing this though because the latest commits fix a lot of crashes, and also add ZDSR support. How should I fix this?

**Comment by Timtam** [comment]
As long as the author doesn't feel like pushing a wheel to PyPI we could add the repo as submodule and build a wheel from that instead.

**Comment by trypsynth** [comment]
Okay, sounds good. How would I go about doing that? I've admittedly never done much with submodules

**Comment by Timtam** [comment]
Correcting myself here, you just need to specify the full address correctly within the requirements.txt file, including the egg name and specific commit/tag/branch to build from for fixed dependency. That should work (given that the commit is the one we should use for now):

```
accessible_output2@git+https://www.github.com/accessibleapps/accessible_output2@327bdea5e0a079bc507e341c1cb4631206675a2d#egg=accessible_output2
```

**Comment by trypsynth** [comment]
@Timtam, done.

**Pull request merged**
